[
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/connections/models/conn_record.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/connections/models/conn_record.py:304:8 Incompatible return type [7]: Expected `ConnRecord` but got `BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/connections/models/conn_record.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/connections/models/conn_record.py:323:8 Incompatible return type [7]: Expected `ConnRecord` but got `BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/connections/models/conn_record.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/connections/models/conn_record.py:336:8 Incompatible return type [7]: Expected `ConnRecord` but got `BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/multitenant/admin/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/multitenant/admin/routes.py:232:44 Incompatible parameter type [6]: Expected `WalletRecord` for 1st positional only parameter to call `format_wallet_record` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/multitenant/admin/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/multitenant/admin/routes.py:261:42 Incompatible parameter type [6]: Expected `WalletRecord` for 1st positional only parameter to call `format_wallet_record` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/multitenant/manager.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/multitenant/manager.py:267:43 Incompatible parameter type [6]: Expected `WalletRecord` for 2nd positional only parameter to call `MultitenantManager.get_webhook_urls` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/multitenant/manager.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/multitenant/manager.py:272:8 Incompatible return type [7]: Expected `WalletRecord` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/multitenant/manager.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/multitenant/manager.py:423:61 Incompatible parameter type [6]: Expected `WalletRecord` for 2nd positional only parameter to call `MultitenantManager.get_wallet_profile` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/multitenant/manager.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/multitenant/manager.py:444:12 Incompatible return type [7]: Expected `Optional[WalletRecord]` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/connections/v1_0/manager.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/connections/v1_0/manager.py:348:8 Incompatible return type [7]: Expected `ConnRecord` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/connections/v1_0/manager.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/connections/v1_0/manager.py:624:8 Incompatible return type [7]: Expected `ConnRecord` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/connections/v1_0/manager.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/connections/v1_0/manager.py:850:12 Incompatible parameter type [6]: Expected `ConnRecord` for 2nd parameter `connection` to call `ConnectionManager.get_connection_targets` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/connections/v1_0/manager.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/connections/v1_0/manager.py:1036:8 Incompatible return type [7]: Expected `ConnRecord` but got `typing.Union[None, ConnRecord, aries_cloudagent.messaging.models.base_record.BaseRecord]`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/connections/v1_0/manager.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/connections/v1_0/manager.py:1105:24 Incompatible variable type [9]: connection is declared to have type `ConnRecord` but is used as type `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/connections/v1_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/connections/v1_0/routes.py:613:16 Incompatible parameter type [6]: Expected `ConnRecord` for 1st positional only parameter to call `ConnectionManager.create_request` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/connections/v1_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/connections/v1_0/routes.py:658:56 Incompatible parameter type [6]: Expected `ConnRecord` for 1st positional only parameter to call `ConnectionManager.create_response` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/connections/v1_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/connections/v1_0/routes.py:691:12 Incompatible parameter type [6]: Expected `ConnRecord` for 1st positional only parameter to call `ConnectionManager.establish_inbound` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/coordinate_mediation/v1_0/manager.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/coordinate_mediation/v1_0/manager.py:185:8 Incompatible return type [7]: Expected `Tuple[MediationRecord, MediationGrant]` but got `Tuple[aries_cloudagent.messaging.models.base_record.BaseRecord, MediationGrant]`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/coordinate_mediation/v1_0/manager.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/coordinate_mediation/v1_0/manager.py:222:8 Incompatible return type [7]: Expected `Tuple[MediationRecord, MediationDeny]` but got `Tuple[aries_cloudagent.messaging.models.base_record.BaseRecord, MediationDeny]`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/coordinate_mediation/v1_0/manager.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/coordinate_mediation/v1_0/manager.py:356:16 Incompatible return type [7]: Expected `Optional[MediationRecord]` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/coordinate_mediation/v1_0/manager.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/coordinate_mediation/v1_0/manager.py:609:12 Incompatible return type [7]: Expected `Sequence[RouteRecord]` but got `Sequence[aries_cloudagent.messaging.models.base_record.BaseRecord]`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/coordinate_mediation/v1_0/models/mediation_record.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/coordinate_mediation/v1_0/models/mediation_record.py:133:8 Incompatible return type [7]: Expected `MediationRecord` but got `BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/didexchange/v1_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/didexchange/v1_0/routes.py:146:12 Incompatible parameter type [6]: Expected `ConnRecord` for 1st parameter `conn_rec` to call `DIDXManager.create_request` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/didexchange/v1_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/didexchange/v1_0/routes.py:282:12 Incompatible parameter type [6]: Expected `ConnRecord` for 1st parameter `conn_rec` to call `DIDXManager.create_response` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/endorse_transaction/v1_0/models/transaction_record.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/endorse_transaction/v1_0/models/transaction_record.py:125:8 Incompatible return type [7]: Expected `TransactionRecord` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/endorse_transaction/v1_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/endorse_transaction/v1_0/routes.py:259:12 Incompatible parameter type [6]: Expected `TransactionRecord` for 1st parameter `transaction` to call `TransactionManager.create_request` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/endorse_transaction/v1_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/endorse_transaction/v1_0/routes.py:360:12 Incompatible parameter type [6]: Expected `TransactionRecord` for 1st parameter `transaction` to call `TransactionManager.create_endorse_response` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/endorse_transaction/v1_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/endorse_transaction/v1_0/routes.py:442:12 Incompatible parameter type [6]: Expected `TransactionRecord` for 1st parameter `transaction` to call `TransactionManager.create_refuse_response` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/endorse_transaction/v1_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/endorse_transaction/v1_0/routes.py:509:12 Incompatible parameter type [6]: Expected `TransactionRecord` for 1st parameter `transaction` to call `TransactionManager.cancel_transaction` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/endorse_transaction/v1_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/endorse_transaction/v1_0/routes.py:574:12 Incompatible parameter type [6]: Expected `TransactionRecord` for 1st parameter `transaction` to call `TransactionManager.transaction_resend` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/endorse_transaction/v1_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/endorse_transaction/v1_0/routes.py:618:8 Incompatible parameter type [6]: Expected `ConnRecord` for 1st parameter `record` to call `TransactionManager.set_transaction_my_job` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/endorse_transaction/v1_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/endorse_transaction/v1_0/routes.py:733:55 Incompatible parameter type [6]: Expected `TransactionRecord` for 1st parameter `transaction` to call `TransactionManager.complete_transaction` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/issue_credential/v1_0/models/credential_exchange.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/issue_credential/v1_0/models/credential_exchange.py:276:8 Incompatible return type [7]: Expected `V10CredentialExchange` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/issue_credential/v1_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/issue_credential/v1_0/routes.py:539:12 Incompatible parameter type [6]: Expected `typing.Union[ConnRecord, V10CredentialExchange]` for 4th positional only parameter to call `report_problem` but got `typing.Optional[aries_cloudagent.messaging.models.base_record.BaseRecord]`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/issue_credential/v1_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/issue_credential/v1_0/routes.py:617:12 Incompatible parameter type [6]: Expected `typing.Union[ConnRecord, V10CredentialExchange]` for 4th positional only parameter to call `report_problem` but got `typing.Optional[aries_cloudagent.messaging.models.base_record.BaseRecord]`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/issue_credential/v1_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/issue_credential/v1_0/routes.py:829:12 Incompatible parameter type [6]: Expected `typing.Union[ConnRecord, V10CredentialExchange]` for 4th positional only parameter to call `report_problem` but got `typing.Optional[aries_cloudagent.messaging.models.base_record.BaseRecord]`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/issue_credential/v1_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/issue_credential/v1_0/routes.py:905:12 Incompatible parameter type [6]: Expected `V10CredentialExchange` for 1st positional only parameter to call `CredentialManager.create_offer` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/issue_credential/v1_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/issue_credential/v1_0/routes.py:928:12 Incompatible parameter type [6]: Expected `typing.Union[ConnRecord, V10CredentialExchange]` for 4th positional only parameter to call `report_problem` but got `typing.Optional[aries_cloudagent.messaging.models.base_record.BaseRecord]`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/issue_credential/v1_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/issue_credential/v1_0/routes.py:992:12 Incompatible parameter type [6]: Expected `V10CredentialExchange` for 1st positional only parameter to call `CredentialManager.create_request` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/issue_credential/v1_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/issue_credential/v1_0/routes.py:1011:12 Incompatible parameter type [6]: Expected `typing.Union[ConnRecord, V10CredentialExchange]` for 4th positional only parameter to call `report_problem` but got `typing.Optional[aries_cloudagent.messaging.models.base_record.BaseRecord]`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/issue_credential/v1_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/issue_credential/v1_0/routes.py:1075:54 Incompatible parameter type [6]: Expected `V10CredentialExchange` for 1st positional only parameter to call `CredentialManager.issue_credential` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/issue_credential/v1_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/issue_credential/v1_0/routes.py:1093:12 Incompatible parameter type [6]: Expected `typing.Union[ConnRecord, V10CredentialExchange]` for 4th positional only parameter to call `report_problem` but got `typing.Optional[aries_cloudagent.messaging.models.base_record.BaseRecord]`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/issue_credential/v1_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/issue_credential/v1_0/routes.py:1158:12 Incompatible parameter type [6]: Expected `V10CredentialExchange` for 1st positional only parameter to call `CredentialManager.store_credential` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/issue_credential/v1_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/issue_credential/v1_0/routes.py:1174:12 Incompatible parameter type [6]: Expected `typing.Union[ConnRecord, V10CredentialExchange]` for 4th positional only parameter to call `report_problem` but got `typing.Optional[aries_cloudagent.messaging.models.base_record.BaseRecord]`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/issue_credential/v1_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/issue_credential/v1_0/routes.py:1182:57 Incompatible parameter type [6]: Expected `V10CredentialExchange` for 1st positional only parameter to call `CredentialManager.send_credential_ack` but got `typing.Union[None, typing.Tuple[V10CredentialExchange, aries_cloudagent.protocols.issue_credential.v1_0.messages.credential_ack.CredentialAck], aries_cloudagent.messaging.models.base_record.BaseRecord]`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/issue_credential/v1_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/issue_credential/v1_0/routes.py:1230:47 Incompatible parameter type [6]: Expected `typing.Union[ConnRecord, V10CredentialExchange]` for 1st positional only parameter to call `problem_report_for_record` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/issue_credential/v2_0/manager.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/issue_credential/v2_0/manager.py:449:8 Incompatible return type [7]: Expected `V20CredExRecord` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/issue_credential/v2_0/models/cred_ex_record.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/issue_credential/v2_0/models/cred_ex_record.py:228:8 Incompatible return type [7]: Expected `V20CredExRecord` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/issue_credential/v2_0/models/detail/indy.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/issue_credential/v2_0/models/detail/indy.py:72:8 Incompatible return type [7]: Expected `Sequence[V20CredExRecordIndy]` but got `Sequence[BaseRecord]`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/issue_credential/v2_0/models/detail/ld_proof.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/issue_credential/v2_0/models/detail/ld_proof.py:58:8 Incompatible return type [7]: Expected `Sequence[V20CredExRecordLDProof]` but got `Sequence[BaseRecord]`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/issue_credential/v2_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/issue_credential/v2_0/routes.py:446:69 Incompatible parameter type [6]: Expected `V20CredExRecord` for 2nd positional only parameter to call `_get_result_with_details` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/issue_credential/v2_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/issue_credential/v2_0/routes.py:481:65 Incompatible parameter type [6]: Expected `V20CredExRecord` for 2nd positional only parameter to call `_get_result_with_details` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/issue_credential/v2_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/issue_credential/v2_0/routes.py:663:12 Incompatible parameter type [6]: Expected `typing.Union[ConnRecord, V20CredExRecord]` for 4th positional only parameter to call `report_problem` but got `typing.Optional[aries_cloudagent.messaging.models.base_record.BaseRecord]`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/issue_credential/v2_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/issue_credential/v2_0/routes.py:750:12 Incompatible parameter type [6]: Expected `typing.Union[ConnRecord, V20CredExRecord]` for 4th positional only parameter to call `report_problem` but got `typing.Optional[aries_cloudagent.messaging.models.base_record.BaseRecord]`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/issue_credential/v2_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/issue_credential/v2_0/routes.py:949:12 Incompatible parameter type [6]: Expected `typing.Union[ConnRecord, V20CredExRecord]` for 4th positional only parameter to call `report_problem` but got `typing.Optional[aries_cloudagent.messaging.models.base_record.BaseRecord]`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/issue_credential/v2_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/issue_credential/v2_0/routes.py:1024:12 Incompatible parameter type [6]: Expected `V20CredExRecord` for 1st positional only parameter to call `V20CredManager.create_offer` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/issue_credential/v2_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/issue_credential/v2_0/routes.py:1052:12 Incompatible parameter type [6]: Expected `typing.Union[ConnRecord, V20CredExRecord]` for 4th positional only parameter to call `report_problem` but got `typing.Optional[aries_cloudagent.messaging.models.base_record.BaseRecord]`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/issue_credential/v2_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/issue_credential/v2_0/routes.py:1221:12 Incompatible parameter type [6]: Expected `V20CredExRecord` for 1st positional only parameter to call `V20CredManager.create_request` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/issue_credential/v2_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/issue_credential/v2_0/routes.py:1242:12 Incompatible parameter type [6]: Expected `typing.Union[ConnRecord, V20CredExRecord]` for 4th positional only parameter to call `report_problem` but got `typing.Optional[aries_cloudagent.messaging.models.base_record.BaseRecord]`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/issue_credential/v2_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/issue_credential/v2_0/routes.py:1305:12 Incompatible parameter type [6]: Expected `V20CredExRecord` for 1st positional only parameter to call `V20CredManager.issue_credential` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/issue_credential/v2_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/issue_credential/v2_0/routes.py:1326:12 Incompatible parameter type [6]: Expected `typing.Union[ConnRecord, V20CredExRecord]` for 4th positional only parameter to call `report_problem` but got `typing.Optional[aries_cloudagent.messaging.models.base_record.BaseRecord]`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/issue_credential/v2_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/issue_credential/v2_0/routes.py:1390:61 Incompatible parameter type [6]: Expected `V20CredExRecord` for 1st positional only parameter to call `V20CredManager.store_credential` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/issue_credential/v2_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/issue_credential/v2_0/routes.py:1404:12 Incompatible parameter type [6]: Expected `typing.Union[ConnRecord, V20CredExRecord]` for 4th positional only parameter to call `report_problem` but got `typing.Optional[aries_cloudagent.messaging.models.base_record.BaseRecord]`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/issue_credential/v2_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/issue_credential/v2_0/routes.py:1412:45 Incompatible parameter type [6]: Expected `V20CredExRecord` for 1st positional only parameter to call `V20CredManager.send_cred_ack` but got `typing.Union[None, typing.Tuple[V20CredExRecord, aries_cloudagent.protocols.issue_credential.v2_0.messages.cred_ack.V20CredAck], aries_cloudagent.messaging.models.base_record.BaseRecord]`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/issue_credential/v2_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/issue_credential/v2_0/routes.py:1490:47 Incompatible parameter type [6]: Expected `typing.Union[ConnRecord, V20CredExRecord]` for 1st positional only parameter to call `problem_report_for_record` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/out_of_band/v1_0/manager.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/out_of_band/v1_0/manager.py:903:20 Incompatible return type [7]: Expected `Optional[ConnRecord]` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/out_of_band/v1_0/manager.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/out_of_band/v1_0/manager.py:942:16 Incompatible return type [7]: Expected `ConnRecord` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/present_proof/v1_0/handlers/presentation_request_handler.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/present_proof/v1_0/handlers/presentation_request_handler.py:76:12 Incompatible parameter type [6]: Expected `V10PresentationExchange` for 1st positional only parameter to call `PresentationManager.receive_request` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/present_proof/v1_0/manager.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/present_proof/v1_0/manager.py:350:20 Incompatible attribute type [8]: Attribute `state` declared in class `aries_cloudagent.messaging.models.base_record.BaseRecord` has type `str` but is used as type `None`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/present_proof/v1_0/manager.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/present_proof/v1_0/manager.py:499:12 Incompatible attribute type [8]: Attribute `state` declared in class `aries_cloudagent.messaging.models.base_record.BaseRecord` has type `str` but is used as type `None`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/present_proof/v1_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/present_proof/v1_0/routes.py:339:12 Incompatible parameter type [6]: Expected `typing.Union[ConnRecord, V10PresentationExchange]` for 4th positional only parameter to call `report_problem` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/present_proof/v1_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/present_proof/v1_0/routes.py:647:60 Incompatible parameter type [6]: Expected `V10PresentationExchange` for 1st positional only parameter to call `PresentationManager.create_bound_request` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/present_proof/v1_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/present_proof/v1_0/routes.py:658:12 Incompatible parameter type [6]: Expected `typing.Union[ConnRecord, V10PresentationExchange]` for 4th positional only parameter to call `report_problem` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/present_proof/v1_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/present_proof/v1_0/routes.py:734:12 Incompatible parameter type [6]: Expected `V10PresentationExchange` for 1st positional only parameter to call `PresentationManager.create_presentation` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/present_proof/v1_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/present_proof/v1_0/routes.py:758:12 Incompatible parameter type [6]: Expected `typing.Union[ConnRecord, V10PresentationExchange]` for 4th positional only parameter to call `report_problem` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/present_proof/v1_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/present_proof/v1_0/routes.py:832:72 Incompatible parameter type [6]: Expected `V10PresentationExchange` for 1st positional only parameter to call `PresentationManager.verify_presentation` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/present_proof/v1_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/present_proof/v1_0/routes.py:843:12 Incompatible parameter type [6]: Expected `typing.Union[ConnRecord, V10PresentationExchange]` for 4th positional only parameter to call `report_problem` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/present_proof/v1_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/present_proof/v1_0/routes.py:884:47 Incompatible parameter type [6]: Expected `typing.Union[ConnRecord, V10PresentationExchange]` for 1st positional only parameter to call `problem_report_for_record` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/present_proof/v2_0/handlers/pres_request_handler.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/present_proof/v2_0/handlers/pres_request_handler.py:72:12 Incompatible parameter type [6]: Expected `V20PresExRecord` for 1st positional only parameter to call `V20PresManager.receive_pres_request` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/present_proof/v2_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/present_proof/v2_0/routes.py:482:12 Incompatible parameter type [6]: Expected `typing.Union[ConnRecord, V20PresExRecord]` for 4th positional only parameter to call `report_problem` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/present_proof/v2_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/present_proof/v2_0/routes.py:625:12 Incompatible parameter type [6]: Expected `typing.Union[ConnRecord, V20PresExRecord]` for 4th positional only parameter to call `report_problem` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/present_proof/v2_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/present_proof/v2_0/routes.py:923:52 Incompatible parameter type [6]: Expected `V20PresExRecord` for 1st positional only parameter to call `V20PresManager.create_bound_request` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/present_proof/v2_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/present_proof/v2_0/routes.py:934:12 Incompatible parameter type [6]: Expected `typing.Union[ConnRecord, V20PresExRecord]` for 4th positional only parameter to call `report_problem` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/present_proof/v2_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/present_proof/v2_0/routes.py:1019:12 Incompatible parameter type [6]: Expected `V20PresExRecord` for 1st positional only parameter to call `V20PresManager.create_pres` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/present_proof/v2_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/present_proof/v2_0/routes.py:1039:12 Incompatible parameter type [6]: Expected `typing.Union[ConnRecord, V20PresExRecord]` for 4th positional only parameter to call `report_problem` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/present_proof/v2_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/present_proof/v2_0/routes.py:1108:56 Incompatible parameter type [6]: Expected `V20PresExRecord` for 1st positional only parameter to call `V20PresManager.verify_pres` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/present_proof/v2_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/present_proof/v2_0/routes.py:1119:12 Incompatible parameter type [6]: Expected `typing.Union[ConnRecord, V20PresExRecord]` for 4th positional only parameter to call `report_problem` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/present_proof/v2_0/routes.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/present_proof/v2_0/routes.py:1158:43 Incompatible parameter type [6]: Expected `typing.Union[ConnRecord, V20PresExRecord]` for 1st positional only parameter to call `problem_report_for_record` but got `aries_cloudagent.messaging.models.base_record.BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/routing/v1_0/manager.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/routing/v1_0/manager.py:108:8 Incompatible return type [7]: Expected `Sequence[RouteRecord]` but got `Sequence[aries_cloudagent.messaging.models.base_record.BaseRecord]`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/routing/v1_0/models/route_record.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/routing/v1_0/models/route_record.py:79:8 Incompatible return type [7]: Expected `RouteRecord` but got `BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/protocols/routing/v1_0/models/route_record.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/protocols/routing/v1_0/models/route_record.py:96:8 Incompatible return type [7]: Expected `RouteRecord` but got `BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/revocation/indy.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/revocation/indy.py:94:12 Incompatible return type [7]: Expected `Sequence[IssuerRevRegRecord]` but got `Sequence[aries_cloudagent.messaging.models.base_record.BaseRecord]`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/revocation/models/issuer_cred_rev_record.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/revocation/models/issuer_cred_rev_record.py:85:8 Incompatible return type [7]: Expected `Sequence[IssuerCredRevRecord]` but got `Sequence[BaseRecord]`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/revocation/models/issuer_cred_rev_record.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/revocation/models/issuer_cred_rev_record.py:95:8 Incompatible return type [7]: Expected `IssuerCredRevRecord` but got `BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/revocation/models/issuer_cred_rev_record.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/revocation/models/issuer_cred_rev_record.py:106:8 Incompatible return type [7]: Expected `IssuerCredRevRecord` but got `BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/revocation/models/issuer_rev_reg_record.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/revocation/models/issuer_rev_reg_record.py:397:8 Incompatible return type [7]: Expected `Sequence[IssuerRevRegRecord]` but got `Sequence[BaseRecord]`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/revocation/models/issuer_rev_reg_record.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/revocation/models/issuer_rev_reg_record.py:408:8 Incompatible return type [7]: Expected `Sequence[IssuerRevRegRecord]` but got `Sequence[BaseRecord]`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  },
  {
    "project": "hyperledger/aries-cloudagent-python",
    "commit": "3f00929ec8e0d432cbae5b2413fce7e5730be635",
    "filename": "aries_cloudagent/revocation/models/issuer_rev_reg_record.py",
    "min_patch_found": false,
    "full_warning_msg": "aries_cloudagent/revocation/models/issuer_rev_reg_record.py:426:8 Incompatible return type [7]: Expected `IssuerRevRegRecord` but got `BaseRecord`.",
    "exception": "PatchSet should only have 1 Patch, but it has 0",
    "dd_fail": true
  }
]