[
  {
    "project": "tensorflow/models",
    "commit": "c5ff4ec7ad1b287cd6d7907569081a2022aa225b",
    "filename": "official/recommendation/data_async_generation.py",
    "min_patch_found": false,
    "full_warning_msg": "official/recommendation/data_async_generation.py:442:37 Incompatible parameter type [6]: Expected `typing.List[str]` for 7th positional only parameter to call `_construct_records` but got `typing.Union[typing.List[typing.Any], int, rconst.Paths]`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/tensorflow-models/official/recommendation/data_async_generation.py'",
    "dd_fail": true
  },
  {
    "project": "tensorflow/models",
    "commit": "c5ff4ec7ad1b287cd6d7907569081a2022aa225b",
    "filename": "official/recommendation/data_async_generation.py",
    "min_patch_found": false,
    "full_warning_msg": "official/recommendation/data_async_generation.py:442:37 Incompatible parameter type [6]: Expected `bool` for 7th positional only parameter to call `_construct_records` but got `typing.Union[typing.List[typing.Any], int, rconst.Paths]`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/tensorflow-models/official/recommendation/data_async_generation.py'",
    "dd_fail": true
  },
  {
    "project": "tensorflow/models",
    "commit": "c5ff4ec7ad1b287cd6d7907569081a2022aa225b",
    "filename": "official/recommendation/data_async_generation.py",
    "min_patch_found": false,
    "full_warning_msg": "official/recommendation/data_async_generation.py:442:37 Incompatible parameter type [6]: Expected `int` for 7th positional only parameter to call `_construct_records` but got `typing.Union[typing.List[typing.Any], int, rconst.Paths]`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/tensorflow-models/official/recommendation/data_async_generation.py'",
    "dd_fail": true
  },
  {
    "project": "tensorflow/models",
    "commit": "c5ff4ec7ad1b287cd6d7907569081a2022aa225b",
    "filename": "official/recommendation/data_async_generation.py",
    "min_patch_found": false,
    "full_warning_msg": "official/recommendation/data_async_generation.py:442:37 Incompatible parameter type [6]: Expected `rconst.Paths` for 7th positional only parameter to call `_construct_records` but got `typing.Union[typing.List[typing.Any], int, rconst.Paths]`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/tensorflow-models/official/recommendation/data_async_generation.py'",
    "dd_fail": true
  },
  {
    "project": "tensorflow/models",
    "commit": "c5ff4ec7ad1b287cd6d7907569081a2022aa225b",
    "filename": "official/recommendation/data_async_generation.py",
    "min_patch_found": false,
    "full_warning_msg": "official/recommendation/data_async_generation.py:449:8 Incompatible parameter type [6]: Expected `typing.List[str]` for 7th positional only parameter to call `_construct_records` but got `typing.Union[typing.List[typing.Any], int, rconst.Paths]`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/tensorflow-models/official/recommendation/data_async_generation.py'",
    "dd_fail": true
  },
  {
    "project": "tensorflow/models",
    "commit": "c5ff4ec7ad1b287cd6d7907569081a2022aa225b",
    "filename": "official/recommendation/data_async_generation.py",
    "min_patch_found": false,
    "full_warning_msg": "official/recommendation/data_async_generation.py:449:8 Incompatible parameter type [6]: Expected `bool` for 7th positional only parameter to call `_construct_records` but got `typing.Union[typing.List[typing.Any], int, rconst.Paths]`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/tensorflow-models/official/recommendation/data_async_generation.py'",
    "dd_fail": true
  },
  {
    "project": "tensorflow/models",
    "commit": "c5ff4ec7ad1b287cd6d7907569081a2022aa225b",
    "filename": "official/recommendation/data_async_generation.py",
    "min_patch_found": false,
    "full_warning_msg": "official/recommendation/data_async_generation.py:449:8 Incompatible parameter type [6]: Expected `int` for 7th positional only parameter to call `_construct_records` but got `typing.Union[typing.List[typing.Any], int, rconst.Paths]`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/tensorflow-models/official/recommendation/data_async_generation.py'",
    "dd_fail": true
  },
  {
    "project": "tensorflow/models",
    "commit": "c5ff4ec7ad1b287cd6d7907569081a2022aa225b",
    "filename": "official/recommendation/data_async_generation.py",
    "min_patch_found": false,
    "full_warning_msg": "official/recommendation/data_async_generation.py:449:8 Incompatible parameter type [6]: Expected `rconst.Paths` for 7th positional only parameter to call `_construct_records` but got `typing.Union[typing.List[typing.Any], int, rconst.Paths]`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/tensorflow-models/official/recommendation/data_async_generation.py'",
    "dd_fail": true
  },
  {
    "project": "tensorflow/models",
    "commit": "c5ff4ec7ad1b287cd6d7907569081a2022aa225b",
    "filename": "official/recommendation/data_async_generation.py",
    "min_patch_found": false,
    "full_warning_msg": "official/recommendation/data_async_generation.py:476:39 Incompatible parameter type [6]: Expected `typing.List[str]` for 7th positional only parameter to call `_construct_records` but got `typing.Union[typing.List[typing.Any], int, rconst.Paths]`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/tensorflow-models/official/recommendation/data_async_generation.py'",
    "dd_fail": true
  },
  {
    "project": "tensorflow/models",
    "commit": "c5ff4ec7ad1b287cd6d7907569081a2022aa225b",
    "filename": "official/recommendation/data_async_generation.py",
    "min_patch_found": false,
    "full_warning_msg": "official/recommendation/data_async_generation.py:476:39 Incompatible parameter type [6]: Expected `bool` for 7th positional only parameter to call `_construct_records` but got `typing.Union[typing.List[typing.Any], int, rconst.Paths]`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/tensorflow-models/official/recommendation/data_async_generation.py'",
    "dd_fail": true
  },
  {
    "project": "tensorflow/models",
    "commit": "c5ff4ec7ad1b287cd6d7907569081a2022aa225b",
    "filename": "official/recommendation/data_async_generation.py",
    "min_patch_found": false,
    "full_warning_msg": "official/recommendation/data_async_generation.py:476:39 Incompatible parameter type [6]: Expected `int` for 7th positional only parameter to call `_construct_records` but got `typing.Union[typing.List[typing.Any], int, rconst.Paths]`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/tensorflow-models/official/recommendation/data_async_generation.py'",
    "dd_fail": true
  },
  {
    "project": "tensorflow/models",
    "commit": "c5ff4ec7ad1b287cd6d7907569081a2022aa225b",
    "filename": "official/recommendation/data_async_generation.py",
    "min_patch_found": false,
    "full_warning_msg": "official/recommendation/data_async_generation.py:476:39 Incompatible parameter type [6]: Expected `rconst.Paths` for 7th positional only parameter to call `_construct_records` but got `typing.Union[typing.List[typing.Any], int, rconst.Paths]`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/tensorflow-models/official/recommendation/data_async_generation.py'",
    "dd_fail": true
  },
  {
    "project": "tensorflow/models",
    "commit": "c5ff4ec7ad1b287cd6d7907569081a2022aa225b",
    "filename": "official/recommendation/data_preprocessing.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/tensorflow-models/official/recommendation/data_preprocessing.py",
    "file_hunks_size": 10,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "official/recommendation/data_preprocessing.py:93:54 Invalid type [31]: Expression `\"(pandas.DataFrame, dict, dict)\"` is not a valid type.",
    "message": " Expression `\"(pandas.DataFrame, dict, dict)\"` is not a valid type.",
    "rule_id": "Invalid type [31]",
    "warning_line_no": 93,
    "warning_line": "def _filter_index_sort(raw_rating_path, match_mlperf):"
  },
  {
    "project": "tensorflow/models",
    "commit": "c5ff4ec7ad1b287cd6d7907569081a2022aa225b",
    "filename": "official/recommendation/data_preprocessing.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/tensorflow-models/official/recommendation/data_preprocessing.py",
    "file_hunks_size": 10,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "official/recommendation/data_preprocessing.py:437:40 Invalid type [31]: Expression `\"(official.recommendation.data_preprocessing.NCFDataset, typing.Callable)\"` is not a valid type.",
    "message": " Expression `\"(official.recommendation.data_preprocessing.NCFDataset, typing.Callable)\"` is not a valid type.",
    "rule_id": "Invalid type [31]",
    "warning_line_no": 437,
    "warning_line": "                         cache_id=None):"
  },
  {
    "project": "tensorflow/models",
    "commit": "c5ff4ec7ad1b287cd6d7907569081a2022aa225b",
    "filename": "official/recommendation/data_preprocessing.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/tensorflow-models/official/recommendation/data_preprocessing.py",
    "file_hunks_size": 10,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "official/recommendation/data_preprocessing.py:605:6 Invalid type [31]: Expression `\"(typing.Callable, str, int)\"` is not a valid type.",
    "message": " Expression `\"(typing.Callable, str, int)\"` is not a valid type.",
    "rule_id": "Invalid type [31]",
    "warning_line_no": 605,
    "warning_line": "    ):"
  }
]