[
  {
    "project": "pantsbuild/pants",
    "commit": "fb3cd10bfc67a5ecf58d1d6b1463de2cf6ae8ab6",
    "filename": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/objects/__init__.py",
    "min_patch_found": false,
    "full_warning_msg": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/objects/__init__.py:9:29 Unbound name [10]: Name `IndexObject` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/pantsbuild-pants/3rdparty/python/GitPython-0.3.1-py2.6.egg/git/objects/__init__.py'",
    "dd_fail": true
  },
  {
    "project": "pantsbuild/pants",
    "commit": "fb3cd10bfc67a5ecf58d1d6b1463de2cf6ae8ab6",
    "filename": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/objects/__init__.py",
    "min_patch_found": false,
    "full_warning_msg": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/objects/__init__.py:10:24 Unbound name [10]: Name `Object` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/pantsbuild-pants/3rdparty/python/GitPython-0.3.1-py2.6.egg/git/objects/__init__.py'",
    "dd_fail": true
  },
  {
    "project": "pantsbuild/pants",
    "commit": "fb3cd10bfc67a5ecf58d1d6b1463de2cf6ae8ab6",
    "filename": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/objects/base.py",
    "min_patch_found": false,
    "full_warning_msg": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/objects/base.py:121:1 Inconsistent override [15]: `__slots__` overrides attribute defined in `Object` inconsistently. Type `typing.Tuple[str, str]` is not a subtype of the overridden attribute `typing.Tuple[str, str, str]`.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/pantsbuild-pants/3rdparty/python/GitPython-0.3.1-py2.6.egg/git/objects/base.py'",
    "dd_fail": true
  },
  {
    "project": "pantsbuild/pants",
    "commit": "fb3cd10bfc67a5ecf58d1d6b1463de2cf6ae8ab6",
    "filename": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/refs/__init__.py",
    "min_patch_found": false,
    "full_warning_msg": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/refs/__init__.py:11:23 Unbound name [10]: Name `RemoteReference` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/pantsbuild-pants/3rdparty/python/GitPython-0.3.1-py2.6.egg/git/refs/__init__.py'",
    "dd_fail": true
  },
  {
    "project": "pantsbuild/pants",
    "commit": "fb3cd10bfc67a5ecf58d1d6b1463de2cf6ae8ab6",
    "filename": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/refs/__init__.py",
    "min_patch_found": false,
    "full_warning_msg": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/refs/__init__.py:16:13 Unbound name [10]: Name `HEAD` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/pantsbuild-pants/3rdparty/python/GitPython-0.3.1-py2.6.egg/git/refs/__init__.py'",
    "dd_fail": true
  },
  {
    "project": "pantsbuild/pants",
    "commit": "fb3cd10bfc67a5ecf58d1d6b1463de2cf6ae8ab6",
    "filename": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/refs/__init__.py",
    "min_patch_found": false,
    "full_warning_msg": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/refs/__init__.py:16:19 Unbound name [10]: Name `Head` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/pantsbuild-pants/3rdparty/python/GitPython-0.3.1-py2.6.egg/git/refs/__init__.py'",
    "dd_fail": true
  },
  {
    "project": "pantsbuild/pants",
    "commit": "fb3cd10bfc67a5ecf58d1d6b1463de2cf6ae8ab6",
    "filename": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/refs/__init__.py",
    "min_patch_found": false,
    "full_warning_msg": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/refs/__init__.py:16:42 Unbound name [10]: Name `TagReference` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/pantsbuild-pants/3rdparty/python/GitPython-0.3.1-py2.6.egg/git/refs/__init__.py'",
    "dd_fail": true
  },
  {
    "project": "pantsbuild/pants",
    "commit": "fb3cd10bfc67a5ecf58d1d6b1463de2cf6ae8ab6",
    "filename": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/refs/__init__.py",
    "min_patch_found": false,
    "full_warning_msg": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/refs/__init__.py:16:56 Unbound name [10]: Name `Reference` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/pantsbuild-pants/3rdparty/python/GitPython-0.3.1-py2.6.egg/git/refs/__init__.py'",
    "dd_fail": true
  },
  {
    "project": "pantsbuild/pants",
    "commit": "fb3cd10bfc67a5ecf58d1d6b1463de2cf6ae8ab6",
    "filename": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/refs/__init__.py",
    "min_patch_found": false,
    "full_warning_msg": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/refs/__init__.py:16:67 Unbound name [10]: Name `SymbolicReference` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/pantsbuild-pants/3rdparty/python/GitPython-0.3.1-py2.6.egg/git/refs/__init__.py'",
    "dd_fail": true
  },
  {
    "project": "pantsbuild/pants",
    "commit": "fb3cd10bfc67a5ecf58d1d6b1463de2cf6ae8ab6",
    "filename": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_base.py",
    "min_patch_found": false,
    "full_warning_msg": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_base.py:86:2 Unbound name [10]: Name `with_rw_repo` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/pantsbuild-pants/3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_base.py'",
    "dd_fail": true
  },
  {
    "project": "pantsbuild/pants",
    "commit": "fb3cd10bfc67a5ecf58d1d6b1463de2cf6ae8ab6",
    "filename": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_base.py",
    "min_patch_found": false,
    "full_warning_msg": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_base.py:96:2 Unbound name [10]: Name `with_rw_and_rw_remote_repo` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/pantsbuild-pants/3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_base.py'",
    "dd_fail": true
  },
  {
    "project": "pantsbuild/pants",
    "commit": "fb3cd10bfc67a5ecf58d1d6b1463de2cf6ae8ab6",
    "filename": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_blob.py",
    "min_patch_found": false,
    "full_warning_msg": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_blob.py:11:15 Unbound name [10]: Name `TestBase` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/pantsbuild-pants/3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_blob.py'",
    "dd_fail": true
  },
  {
    "project": "pantsbuild/pants",
    "commit": "fb3cd10bfc67a5ecf58d1d6b1463de2cf6ae8ab6",
    "filename": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_commit.py",
    "min_patch_found": false,
    "full_warning_msg": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_commit.py:68:17 Unbound name [10]: Name `TestBase` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/pantsbuild-pants/3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_commit.py'",
    "dd_fail": true
  },
  {
    "project": "pantsbuild/pants",
    "commit": "fb3cd10bfc67a5ecf58d1d6b1463de2cf6ae8ab6",
    "filename": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_commit.py",
    "min_patch_found": false,
    "full_warning_msg": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_commit.py:242:2 Unbound name [10]: Name `with_rw_repo` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/pantsbuild-pants/3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_commit.py'",
    "dd_fail": true
  },
  {
    "project": "pantsbuild/pants",
    "commit": "fb3cd10bfc67a5ecf58d1d6b1463de2cf6ae8ab6",
    "filename": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_config.py",
    "min_patch_found": false,
    "full_warning_msg": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_config.py:13:15 Unbound name [10]: Name `TestCase` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/pantsbuild-pants/3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_config.py'",
    "dd_fail": true
  },
  {
    "project": "pantsbuild/pants",
    "commit": "fb3cd10bfc67a5ecf58d1d6b1463de2cf6ae8ab6",
    "filename": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_db.py",
    "min_patch_found": false,
    "full_warning_msg": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_db.py:12:13 Unbound name [10]: Name `TestBase` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/pantsbuild-pants/3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_db.py'",
    "dd_fail": true
  },
  {
    "project": "pantsbuild/pants",
    "commit": "fb3cd10bfc67a5ecf58d1d6b1463de2cf6ae8ab6",
    "filename": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_diff.py",
    "min_patch_found": false,
    "full_warning_msg": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_diff.py:10:15 Unbound name [10]: Name `TestBase` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/pantsbuild-pants/3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_diff.py'",
    "dd_fail": true
  },
  {
    "project": "pantsbuild/pants",
    "commit": "fb3cd10bfc67a5ecf58d1d6b1463de2cf6ae8ab6",
    "filename": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_fun.py",
    "min_patch_found": false,
    "full_warning_msg": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_fun.py:25:14 Unbound name [10]: Name `TestBase` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/pantsbuild-pants/3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_fun.py'",
    "dd_fail": true
  },
  {
    "project": "pantsbuild/pants",
    "commit": "fb3cd10bfc67a5ecf58d1d6b1463de2cf6ae8ab6",
    "filename": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_fun.py",
    "min_patch_found": false,
    "full_warning_msg": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_fun.py:76:2 Unbound name [10]: Name `with_rw_repo` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/pantsbuild-pants/3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_fun.py'",
    "dd_fail": true
  },
  {
    "project": "pantsbuild/pants",
    "commit": "fb3cd10bfc67a5ecf58d1d6b1463de2cf6ae8ab6",
    "filename": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_git.py",
    "min_patch_found": false,
    "full_warning_msg": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_git.py:11:14 Unbound name [10]: Name `TestCase` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/pantsbuild-pants/3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_git.py'",
    "dd_fail": true
  },
  {
    "project": "pantsbuild/pants",
    "commit": "fb3cd10bfc67a5ecf58d1d6b1463de2cf6ae8ab6",
    "filename": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_git.py",
    "min_patch_found": false,
    "full_warning_msg": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_git.py:17:5 Unbound name [10]: Name `patch_object` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/pantsbuild-pants/3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_git.py'",
    "dd_fail": true
  },
  {
    "project": "pantsbuild/pants",
    "commit": "fb3cd10bfc67a5ecf58d1d6b1463de2cf6ae8ab6",
    "filename": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_git.py",
    "min_patch_found": false,
    "full_warning_msg": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_git.py:24:5 Unbound name [10]: Name `raises` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/pantsbuild-pants/3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_git.py'",
    "dd_fail": true
  },
  {
    "project": "pantsbuild/pants",
    "commit": "fb3cd10bfc67a5ecf58d1d6b1463de2cf6ae8ab6",
    "filename": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_index.py",
    "min_patch_found": false,
    "full_warning_msg": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_index.py:17:16 Unbound name [10]: Name `TestBase` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/pantsbuild-pants/3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_index.py'",
    "dd_fail": true
  },
  {
    "project": "pantsbuild/pants",
    "commit": "fb3cd10bfc67a5ecf58d1d6b1463de2cf6ae8ab6",
    "filename": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_index.py",
    "min_patch_found": false,
    "full_warning_msg": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_index.py:105:2 Unbound name [10]: Name `with_rw_repo` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/pantsbuild-pants/3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_index.py'",
    "dd_fail": true
  },
  {
    "project": "pantsbuild/pants",
    "commit": "fb3cd10bfc67a5ecf58d1d6b1463de2cf6ae8ab6",
    "filename": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_reflog.py",
    "min_patch_found": false,
    "full_warning_msg": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_reflog.py:10:17 Unbound name [10]: Name `TestBase` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/pantsbuild-pants/3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_reflog.py'",
    "dd_fail": true
  },
  {
    "project": "pantsbuild/pants",
    "commit": "fb3cd10bfc67a5ecf58d1d6b1463de2cf6ae8ab6",
    "filename": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_remote.py",
    "min_patch_found": false,
    "full_warning_msg": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_remote.py:18:25 Unbound name [10]: Name `RemoteProgress` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/pantsbuild-pants/3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_remote.py'",
    "dd_fail": true
  },
  {
    "project": "pantsbuild/pants",
    "commit": "fb3cd10bfc67a5ecf58d1d6b1463de2cf6ae8ab6",
    "filename": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_remote.py",
    "min_patch_found": false,
    "full_warning_msg": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_remote.py:73:17 Unbound name [10]: Name `TestBase` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/pantsbuild-pants/3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_remote.py'",
    "dd_fail": true
  },
  {
    "project": "pantsbuild/pants",
    "commit": "fb3cd10bfc67a5ecf58d1d6b1463de2cf6ae8ab6",
    "filename": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_remote.py",
    "min_patch_found": false,
    "full_warning_msg": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_remote.py:351:5 Unbound name [10]: Name `with_rw_and_rw_remote_repo` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/pantsbuild-pants/3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_remote.py'",
    "dd_fail": true
  },
  {
    "project": "pantsbuild/pants",
    "commit": "fb3cd10bfc67a5ecf58d1d6b1463de2cf6ae8ab6",
    "filename": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_remote.py",
    "min_patch_found": false,
    "full_warning_msg": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_remote.py:425:5 Unbound name [10]: Name `with_rw_repo` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/pantsbuild-pants/3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_remote.py'",
    "dd_fail": true
  },
  {
    "project": "pantsbuild/pants",
    "commit": "fb3cd10bfc67a5ecf58d1d6b1463de2cf6ae8ab6",
    "filename": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_repo.py",
    "min_patch_found": false,
    "full_warning_msg": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_repo.py:18:15 Unbound name [10]: Name `TestBase` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/pantsbuild-pants/3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_repo.py'",
    "dd_fail": true
  },
  {
    "project": "pantsbuild/pants",
    "commit": "fb3cd10bfc67a5ecf58d1d6b1463de2cf6ae8ab6",
    "filename": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_repo.py",
    "min_patch_found": false,
    "full_warning_msg": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_repo.py:20:2 Unbound name [10]: Name `raises` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/pantsbuild-pants/3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_repo.py'",
    "dd_fail": true
  },
  {
    "project": "pantsbuild/pants",
    "commit": "fb3cd10bfc67a5ecf58d1d6b1463de2cf6ae8ab6",
    "filename": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_repo.py",
    "min_patch_found": false,
    "full_warning_msg": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_repo.py:20:9 Unbound name [10]: Name `InvalidGitRepositoryError` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/pantsbuild-pants/3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_repo.py'",
    "dd_fail": true
  },
  {
    "project": "pantsbuild/pants",
    "commit": "fb3cd10bfc67a5ecf58d1d6b1463de2cf6ae8ab6",
    "filename": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_repo.py",
    "min_patch_found": false,
    "full_warning_msg": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_repo.py:24:9 Unbound name [10]: Name `NoSuchPathError` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/pantsbuild-pants/3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_repo.py'",
    "dd_fail": true
  },
  {
    "project": "pantsbuild/pants",
    "commit": "fb3cd10bfc67a5ecf58d1d6b1463de2cf6ae8ab6",
    "filename": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_repo.py",
    "min_patch_found": false,
    "full_warning_msg": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_repo.py:245:2 Unbound name [10]: Name `patch_object` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/pantsbuild-pants/3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_repo.py'",
    "dd_fail": true
  },
  {
    "project": "pantsbuild/pants",
    "commit": "fb3cd10bfc67a5ecf58d1d6b1463de2cf6ae8ab6",
    "filename": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_repo.py",
    "min_patch_found": false,
    "full_warning_msg": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_repo.py:245:15 Unbound name [10]: Name `Git` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/pantsbuild-pants/3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_repo.py'",
    "dd_fail": true
  },
  {
    "project": "pantsbuild/pants",
    "commit": "fb3cd10bfc67a5ecf58d1d6b1463de2cf6ae8ab6",
    "filename": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_repo.py",
    "min_patch_found": false,
    "full_warning_msg": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_repo.py:590:2 Unbound name [10]: Name `with_rw_repo` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/pantsbuild-pants/3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_repo.py'",
    "dd_fail": true
  },
  {
    "project": "pantsbuild/pants",
    "commit": "fb3cd10bfc67a5ecf58d1d6b1463de2cf6ae8ab6",
    "filename": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_stats.py",
    "min_patch_found": false,
    "full_warning_msg": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_stats.py:10:16 Unbound name [10]: Name `TestBase` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/pantsbuild-pants/3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_stats.py'",
    "dd_fail": true
  },
  {
    "project": "pantsbuild/pants",
    "commit": "fb3cd10bfc67a5ecf58d1d6b1463de2cf6ae8ab6",
    "filename": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_submodule.py",
    "min_patch_found": false,
    "full_warning_msg": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_submodule.py:21:20 Unbound name [10]: Name `TestBase` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/pantsbuild-pants/3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_submodule.py'",
    "dd_fail": true
  },
  {
    "project": "pantsbuild/pants",
    "commit": "fb3cd10bfc67a5ecf58d1d6b1463de2cf6ae8ab6",
    "filename": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_submodule.py",
    "min_patch_found": false,
    "full_warning_msg": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_submodule.py:360:2 Unbound name [10]: Name `with_rw_repo` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/pantsbuild-pants/3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_submodule.py'",
    "dd_fail": true
  },
  {
    "project": "pantsbuild/pants",
    "commit": "fb3cd10bfc67a5ecf58d1d6b1463de2cf6ae8ab6",
    "filename": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_tree.py",
    "min_patch_found": false,
    "full_warning_msg": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_tree.py:16:15 Unbound name [10]: Name `TestBase` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/pantsbuild-pants/3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_tree.py'",
    "dd_fail": true
  },
  {
    "project": "pantsbuild/pants",
    "commit": "fb3cd10bfc67a5ecf58d1d6b1463de2cf6ae8ab6",
    "filename": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_util.py",
    "min_patch_found": false,
    "full_warning_msg": "3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_util.py:19:16 Unbound name [10]: Name `TestBase` is used but not defined in the current scope.",
    "exception": "[Errno 2] No such file or directory: '/home/chowyi/TypeAnnotation_Study/GitHub/pantsbuild-pants/3rdparty/python/GitPython-0.3.1-py2.6.egg/git/test/test_util.py'",
    "dd_fail": true
  }
]