[
  {
    "project": "hikari-py/hikari",
    "commit": "c15c45730399135e5325f4b0c959c20f99c9b9b5",
    "filename": "hikari/model/service_status.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/hikari-py-hikari/hikari/model/service_status.py",
    "file_hunks_size": 1,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "hikari/model/service_status.py:71:76 Incompatible parameter type [6]: Expected `typing.Type[Variable[utils.T]]` for 3rd positional only parameter to call `utils.get_from_map_as` but got `typing.Callable(utils.parse_iso_8601_datetime)[[Named(date_string, str)], datetime.datetime]`.",
    "message": " Expected `typing.Type[Variable[utils.T]]` for 3rd positional only parameter to call `utils.get_from_map_as` but got `typing.Callable(utils.parse_iso_8601_datetime)[[Named(date_string, str)], datetime.datetime]`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 71,
    "warning_line": "            quarantined_at=utils.get_from_map_as(payload, \"quarantined_at\", utils.parse_iso_8601_datetime),"
  },
  {
    "project": "hikari-py/hikari",
    "commit": "c15c45730399135e5325f4b0c959c20f99c9b9b5",
    "filename": "hikari/model/service_status.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/hikari-py-hikari/hikari/model/service_status.py",
    "file_hunks_size": 1,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "hikari/model/service_status.py:74:64 Incompatible parameter type [6]: Expected `typing.Type[Variable[utils.T]]` for 3rd positional only parameter to call `utils.get_from_map_as` but got `typing.Callable(utils.parse_iso_8601_datetime)[[Named(date_string, str)], datetime.datetime]`.",
    "message": " Expected `typing.Type[Variable[utils.T]]` for 3rd positional only parameter to call `utils.get_from_map_as` but got `typing.Callable(utils.parse_iso_8601_datetime)[[Named(date_string, str)], datetime.datetime]`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 74,
    "warning_line": "            purge_at=utils.get_from_map_as(payload, \"purge_at\", utils.parse_iso_8601_datetime),"
  },
  {
    "project": "hikari-py/hikari",
    "commit": "c15c45730399135e5325f4b0c959c20f99c9b9b5",
    "filename": "hikari/model/service_status.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/hikari-py-hikari/hikari/model/service_status.py",
    "file_hunks_size": 1,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "hikari/model/service_status.py:105:68 Incompatible parameter type [6]: Expected `typing.Type[Variable[utils.T]]` for 3rd positional only parameter to call `utils.get_from_map_as` but got `typing.Callable(utils.parse_iso_8601_datetime)[[Named(date_string, str)], datetime.datetime]`.",
    "message": " Expected `typing.Type[Variable[utils.T]]` for 3rd positional only parameter to call `utils.get_from_map_as` but got `typing.Callable(utils.parse_iso_8601_datetime)[[Named(date_string, str)], datetime.datetime]`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 105,
    "warning_line": "            updated_at=utils.get_from_map_as(payload, \"updated_at\", utils.parse_iso_8601_datetime),"
  },
  {
    "project": "hikari-py/hikari",
    "commit": "c15c45730399135e5325f4b0c959c20f99c9b9b5",
    "filename": "hikari/model/service_status.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/hikari-py-hikari/hikari/model/service_status.py",
    "file_hunks_size": 1,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "hikari/model/service_status.py:143:68 Incompatible parameter type [6]: Expected `typing.Type[Variable[utils.T]]` for 3rd positional only parameter to call `utils.get_from_map_as` but got `typing.Callable(utils.parse_iso_8601_datetime)[[Named(date_string, str)], datetime.datetime]`.",
    "message": " Expected `typing.Type[Variable[utils.T]]` for 3rd positional only parameter to call `utils.get_from_map_as` but got `typing.Callable(utils.parse_iso_8601_datetime)[[Named(date_string, str)], datetime.datetime]`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 143,
    "warning_line": "            created_at=utils.get_from_map_as(payload, \"created_at\", utils.parse_iso_8601_datetime),"
  },
  {
    "project": "hikari-py/hikari",
    "commit": "c15c45730399135e5325f4b0c959c20f99c9b9b5",
    "filename": "hikari/model/service_status.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/hikari-py-hikari/hikari/model/service_status.py",
    "file_hunks_size": 1,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "hikari/model/service_status.py:146:68 Incompatible parameter type [6]: Expected `typing.Type[Variable[utils.T]]` for 3rd positional only parameter to call `utils.get_from_map_as` but got `typing.Callable(utils.parse_iso_8601_datetime)[[Named(date_string, str)], datetime.datetime]`.",
    "message": " Expected `typing.Type[Variable[utils.T]]` for 3rd positional only parameter to call `utils.get_from_map_as` but got `typing.Callable(utils.parse_iso_8601_datetime)[[Named(date_string, str)], datetime.datetime]`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 146,
    "warning_line": "            updated_at=utils.get_from_map_as(payload, \"updated_at\", utils.parse_iso_8601_datetime),"
  },
  {
    "project": "hikari-py/hikari",
    "commit": "c15c45730399135e5325f4b0c959c20f99c9b9b5",
    "filename": "hikari/model/service_status.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/hikari-py-hikari/hikari/model/service_status.py",
    "file_hunks_size": 1,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "hikari/model/service_status.py:189:68 Incompatible parameter type [6]: Expected `typing.Type[Variable[utils.T]]` for 3rd positional only parameter to call `utils.get_from_map_as` but got `typing.Callable(utils.parse_iso_8601_datetime)[[Named(date_string, str)], datetime.datetime]`.",
    "message": " Expected `typing.Type[Variable[utils.T]]` for 3rd positional only parameter to call `utils.get_from_map_as` but got `typing.Callable(utils.parse_iso_8601_datetime)[[Named(date_string, str)], datetime.datetime]`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 189,
    "warning_line": "            created_at=utils.get_from_map_as(payload, \"created_at\", utils.parse_iso_8601_datetime),"
  },
  {
    "project": "hikari-py/hikari",
    "commit": "c15c45730399135e5325f4b0c959c20f99c9b9b5",
    "filename": "hikari/model/service_status.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/hikari-py-hikari/hikari/model/service_status.py",
    "file_hunks_size": 1,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "hikari/model/service_status.py:190:68 Incompatible parameter type [6]: Expected `typing.Type[Variable[utils.T]]` for 3rd positional only parameter to call `utils.get_from_map_as` but got `typing.Callable(utils.parse_iso_8601_datetime)[[Named(date_string, str)], datetime.datetime]`.",
    "message": " Expected `typing.Type[Variable[utils.T]]` for 3rd positional only parameter to call `utils.get_from_map_as` but got `typing.Callable(utils.parse_iso_8601_datetime)[[Named(date_string, str)], datetime.datetime]`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 190,
    "warning_line": "            display_at=utils.get_from_map_as(payload, \"display_at\", utils.parse_iso_8601_datetime),"
  },
  {
    "project": "hikari-py/hikari",
    "commit": "c15c45730399135e5325f4b0c959c20f99c9b9b5",
    "filename": "hikari/model/service_status.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/hikari-py-hikari/hikari/model/service_status.py",
    "file_hunks_size": 1,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "hikari/model/service_status.py:193:68 Incompatible parameter type [6]: Expected `typing.Type[Variable[utils.T]]` for 3rd positional only parameter to call `utils.get_from_map_as` but got `typing.Callable(utils.parse_iso_8601_datetime)[[Named(date_string, str)], datetime.datetime]`.",
    "message": " Expected `typing.Type[Variable[utils.T]]` for 3rd positional only parameter to call `utils.get_from_map_as` but got `typing.Callable(utils.parse_iso_8601_datetime)[[Named(date_string, str)], datetime.datetime]`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 193,
    "warning_line": "            updated_at=utils.get_from_map_as(payload, \"updated_at\", utils.parse_iso_8601_datetime),"
  },
  {
    "project": "hikari-py/hikari",
    "commit": "c15c45730399135e5325f4b0c959c20f99c9b9b5",
    "filename": "hikari/model/service_status.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/hikari-py-hikari/hikari/model/service_status.py",
    "file_hunks_size": 1,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "hikari/model/service_status.py:222:39 Incompatible parameter type [6]: Expected `typing.Type[Variable[utils.T]]` for 3rd positional only parameter to call `utils.get_from_map_as` but got `typing.Callable(utils.parse_iso_8601_datetime)[[Named(date_string, str)], datetime.datetime]`.",
    "message": " Expected `typing.Type[Variable[utils.T]]` for 3rd positional only parameter to call `utils.get_from_map_as` but got `typing.Callable(utils.parse_iso_8601_datetime)[[Named(date_string, str)], datetime.datetime]`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 222,
    "warning_line": "                payload, \"updated_at\", utils.parse_iso_8601_datetime, default_on_error=True"
  },
  {
    "project": "hikari-py/hikari",
    "commit": "c15c45730399135e5325f4b0c959c20f99c9b9b5",
    "filename": "hikari/model/service_status.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/hikari-py-hikari/hikari/model/service_status.py",
    "file_hunks_size": 1,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "hikari/model/service_status.py:226:42 Incompatible parameter type [6]: Expected `typing.Type[Variable[utils.T]]` for 3rd positional only parameter to call `utils.get_from_map_as` but got `typing.Callable(utils.parse_iso_8601_datetime)[[Named(date_string, str)], datetime.datetime]`.",
    "message": " Expected `typing.Type[Variable[utils.T]]` for 3rd positional only parameter to call `utils.get_from_map_as` but got `typing.Callable(utils.parse_iso_8601_datetime)[[Named(date_string, str)], datetime.datetime]`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 226,
    "warning_line": "                payload, \"monitoring_at\", utils.parse_iso_8601_datetime, default_on_error=True"
  },
  {
    "project": "hikari-py/hikari",
    "commit": "c15c45730399135e5325f4b0c959c20f99c9b9b5",
    "filename": "hikari/model/service_status.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/hikari-py-hikari/hikari/model/service_status.py",
    "file_hunks_size": 1,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "hikari/model/service_status.py:229:40 Incompatible parameter type [6]: Expected `typing.Type[Variable[utils.T]]` for 3rd positional only parameter to call `utils.get_from_map_as` but got `typing.Callable(utils.parse_iso_8601_datetime)[[Named(date_string, str)], datetime.datetime]`.",
    "message": " Expected `typing.Type[Variable[utils.T]]` for 3rd positional only parameter to call `utils.get_from_map_as` but got `typing.Callable(utils.parse_iso_8601_datetime)[[Named(date_string, str)], datetime.datetime]`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 229,
    "warning_line": "                payload, \"resolved_at\", utils.parse_iso_8601_datetime, default_on_error=True"
  }
]