[
  {
    "project": "encode/starlette",
    "commit": "214d1f1fe677fc35eef8526158975d0ad0521c99",
    "filename": "starlette/testclient.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/encode-starlette/starlette/testclient.py",
    "file_hunks_size": 1,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "starlette/testclient.py:404:8 Incompatible variable type [9]: auth is declared to have type `typing.Union[typing.Callable[[requests.models.Request], requests.models.Request], typing.Tuple[str, str], requests.auth.AuthBase]` but is used as type `None`.",
    "message": " auth is declared to have type `typing.Union[typing.Callable[[requests.models.Request], requests.models.Request], typing.Tuple[str, str], requests.auth.AuthBase]` but is used as type `None`.",
    "rule_id": "Incompatible variable type [9]",
    "warning_line_no": 404,
    "warning_line": "        auth: AuthType = None,"
  },
  {
    "project": "encode/starlette",
    "commit": "214d1f1fe677fc35eef8526158975d0ad0521c99",
    "filename": "starlette/testclient.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/encode-starlette/starlette/testclient.py",
    "file_hunks_size": 1,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "starlette/testclient.py:423:12 Incompatible parameter type [6]: Expected `typing.Union[typing.Callable[[requests.models.PreparedRequest], requests.models.PreparedRequest], None, typing.Tuple[str, str], requests.auth.AuthBase]` for 8th parameter `auth` to call `requests.sessions.Session.request` but got `typing.Union[typing.Callable[[requests.models.Request], requests.models.Request], typing.Tuple[str, str], requests.auth.AuthBase]`.",
    "message": " Expected `typing.Union[typing.Callable[[requests.models.PreparedRequest], requests.models.PreparedRequest], None, typing.Tuple[str, str], requests.auth.AuthBase]` for 8th parameter `auth` to call `requests.sessions.Session.request` but got `typing.Union[typing.Callable[[requests.models.Request], requests.models.Request], typing.Tuple[str, str], requests.auth.AuthBase]`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 423,
    "warning_line": "            auth=auth,"
  }
]