[
  {
    "project": "ipython/ipython",
    "commit": "a2d5071a97e033fbda1782bad322e13f6eab81a3",
    "filename": "IPython/core/completer.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/ipython-ipython/IPython/core/completer.py",
    "file_hunks_size": 9,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "IPython/core/completer.py:428:4 Incompatible variable type [9]: completions is declared to have type `Iterator[Completion]` but is used as type `List[Completion]`.",
    "message": " completions is declared to have type `Iterator[Completion]` but is used as type `List[Completion]`.",
    "rule_id": "Incompatible variable type [9]",
    "warning_line_no": 428,
    "warning_line": "    completions = list(completions)"
  },
  {
    "project": "ipython/ipython",
    "commit": "a2d5071a97e033fbda1782bad322e13f6eab81a3",
    "filename": "IPython/core/completer.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/ipython-ipython/IPython/core/completer.py",
    "file_hunks_size": 9,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "IPython/core/completer.py:474:4 Incompatible variable type [9]: completions is declared to have type `Iterator[Completion]` but is used as type `List[Completion]`.",
    "message": " completions is declared to have type `Iterator[Completion]` but is used as type `List[Completion]`.",
    "rule_id": "Incompatible variable type [9]",
    "warning_line_no": 474,
    "warning_line": "    completions = list(completions)"
  },
  {
    "project": "ipython/ipython",
    "commit": "a2d5071a97e033fbda1782bad322e13f6eab81a3",
    "filename": "IPython/core/completer.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/ipython-ipython/IPython/core/completer.py",
    "file_hunks_size": 9,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "IPython/core/completer.py:833:47 Invalid type [31]: Expression `(int, int)` is not a valid type.",
    "message": " Expression `(int, int)` is not a valid type.",
    "rule_id": "Invalid type [31]",
    "warning_line_no": 833,
    "warning_line": "def position_to_cursor(text:str, offset:int)->(int, int):"
  },
  {
    "project": "ipython/ipython",
    "commit": "a2d5071a97e033fbda1782bad322e13f6eab81a3",
    "filename": "IPython/core/completer.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/ipython-ipython/IPython/core/completer.py",
    "file_hunks_size": 9,
    "min_patch_found": true,
    "single_hunk": true,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "IPython/core/completer.py:1248:36 Incompatible parameter type [6]: Expected `int` for 1st positional only parameter to call `cursor_to_position` but got `str`.",
    "message": " Expected `int` for 1st positional only parameter to call `cursor_to_position` but got `str`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 1248,
    "warning_line": "        offset = cursor_to_position(text, cursor_line, cursor_column)",
    "min_patch": [
      {
        "hunk_fit_TFix": false,
        "inside_window": false,
        "delete_only": false,
        "has_suppression": false,
        "source_code": "\ndef cursor_to_position(text:int, line:int, column:int)->int:\n    \"\"\"\n",
        "source_code_len": 70,
        "target_code": "\ndef cursor_to_position(text:str, line:int, column:int)->int:\n    \"\"\"\n",
        "target_code_len": 70,
        "diff_format": "@@ -802,3 +802,3 @@\n \n-def cursor_to_position(text:int, line:int, column:int)->int:\n+def cursor_to_position(text:str, line:int, column:int)->int:\n     \"\"\"\n",
        "source_code_with_indent_exact_match": false,
        "target_code_with_indent_exact_match": false,
        "source_code_with_indent": "\n<DED>def cursor_to_position(text:int, line:int, column:int)->int:\n    <IND>",
        "target_code_with_indent": "\n<DED>def cursor_to_position(text:str, line:int, column:int)->int:\n    <IND>"
      }
    ]
  },
  {
    "project": "ipython/ipython",
    "commit": "a2d5071a97e033fbda1782bad322e13f6eab81a3",
    "filename": "IPython/core/completer.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/ipython-ipython/IPython/core/completer.py",
    "file_hunks_size": 9,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "IPython/core/completer.py:1831:64 Invalid type [31]: Expression `(str, typing.List[str], typing.List[object])` is not a valid type.",
    "message": " Expression `(str, typing.List[str], typing.List[object])` is not a valid type.",
    "rule_id": "Invalid type [31]",
    "warning_line_no": 1831,
    "warning_line": "                  full_text=None, return_jedi_results=True) -> (str, List[str], List[object]):"
  },
  {
    "project": "ipython/ipython",
    "commit": "a2d5071a97e033fbda1782bad322e13f6eab81a3",
    "filename": "IPython/core/completer.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/ipython-ipython/IPython/core/completer.py",
    "file_hunks_size": 9,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "IPython/core/completer.py:1910:40 Incompatible parameter type [6]: Expected `typing.Type[BaseException]` for 1st positional only parameter to anonymous call but got `typing.Union[None, typing.Type[BaseException], BaseException, types.TracebackType]`.",
    "message": " Expected `typing.Type[BaseException]` for 1st positional only parameter to anonymous call but got `typing.Union[None, typing.Type[BaseException], BaseException, types.TracebackType]`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 1910,
    "warning_line": "                        sys.excepthook(*sys.exc_info())"
  },
  {
    "project": "ipython/ipython",
    "commit": "a2d5071a97e033fbda1782bad322e13f6eab81a3",
    "filename": "IPython/core/completer.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/ipython-ipython/IPython/core/completer.py",
    "file_hunks_size": 9,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "IPython/core/completer.py:1910:40 Incompatible parameter type [6]: Expected `BaseException` for 1st positional only parameter to anonymous call but got `typing.Union[None, typing.Type[BaseException], BaseException, types.TracebackType]`.",
    "message": " Expected `BaseException` for 1st positional only parameter to anonymous call but got `typing.Union[None, typing.Type[BaseException], BaseException, types.TracebackType]`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 1910,
    "warning_line": "                        sys.excepthook(*sys.exc_info())"
  },
  {
    "project": "ipython/ipython",
    "commit": "a2d5071a97e033fbda1782bad322e13f6eab81a3",
    "filename": "IPython/core/completer.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/ipython-ipython/IPython/core/completer.py",
    "file_hunks_size": 9,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "IPython/core/completer.py:1910:40 Incompatible parameter type [6]: Expected `types.TracebackType` for 1st positional only parameter to anonymous call but got `typing.Union[None, typing.Type[BaseException], BaseException, types.TracebackType]`.",
    "message": " Expected `types.TracebackType` for 1st positional only parameter to anonymous call but got `typing.Union[None, typing.Type[BaseException], BaseException, types.TracebackType]`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 1910,
    "warning_line": "                        sys.excepthook(*sys.exc_info())"
  }
]