[
  {
    "project": "googleapis/python-aiplatform",
    "commit": "4459fffe3711c92db085b5049e4076b438ac0ad6",
    "filename": "google/cloud/aiplatform/datasets.py",
    "min_patch_found": false,
    "full_warning_msg": "google/cloud/aiplatform/datasets.py:40:4 Inconsistent override [15]: `client_class` overrides attribute defined in `base.AiPlatformResourceNoun` inconsistently. Type `typing.Type[google.cloud.aiplatform_v1beta1.services.dataset_service.client.DatasetServiceClient]` is not a subtype of the overridden attribute `Variable[utils.AiPlatformServiceClient <: [google.cloud.aiplatform_v1beta1.services.dataset_service.client.DatasetServiceClient, google.cloud.aiplatform_v1beta1.services.endpoint_service.client.EndpointServiceClient, google.cloud.aiplatform_v1beta1.services.model_service.client.ModelServiceClient, google.cloud.aiplatform_v1beta1.services.prediction_service.client.PredictionServiceClient, google.cloud.aiplatform_v1beta1.services.pipeline_service.client.PipelineServiceClient, google.cloud.aiplatform_v1beta1.services.job_service.client.JobServiceClient]]`.",
    "exception": "too many values to unpack (expected 2)",
    "dd_fail": true
  },
  {
    "project": "googleapis/python-aiplatform",
    "commit": "4459fffe3711c92db085b5049e4076b438ac0ad6",
    "filename": "google/cloud/aiplatform/datasets.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/googleapis-python-aiplatform/google/cloud/aiplatform/datasets/dataset.py",
    "file_hunks_size": 30,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "google/cloud/aiplatform/datasets.py:311:12 Incompatible parameter type [6]: Expected `Dict[typing.Any, typing.Any]` for 4th parameter `dataset_metadata` to call `Dataset._create` but got `str`.",
    "message": " Expected `Dict[typing.Any, typing.Any]` for 4th parameter `dataset_metadata` to call `Dataset._create` but got `str`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 311,
    "warning_line": "            dataset_metadata=dataset_metadata,"
  },
  {
    "project": "googleapis/python-aiplatform",
    "commit": "4459fffe3711c92db085b5049e4076b438ac0ad6",
    "filename": "google/cloud/aiplatform/datasets.py",
    "filename_after_commit": "/home/chowyi/TypeAnnotation_Study/GitHub/googleapis-python-aiplatform/google/cloud/aiplatform/datasets/dataset.py",
    "file_hunks_size": 30,
    "min_patch_found": false,
    "single_hunk": false,
    "fit_TFix": false,
    "delete_only_patch": false,
    "has_suppression_all_hunks": false,
    "full_warning_msg": "google/cloud/aiplatform/datasets.py:312:12 Incompatible parameter type [6]: Expected `Sequence[Tuple[str, str]]` for 5th parameter `request_metadata` to call `Dataset._create` but got `str`.",
    "message": " Expected `Sequence[Tuple[str, str]]` for 5th parameter `request_metadata` to call `Dataset._create` but got `str`.",
    "rule_id": "Incompatible parameter type [6]",
    "warning_line_no": 312,
    "warning_line": "            request_metadata=request_metadata,"
  }
]